---
title: "Model 2"
output:
  html_document:
    toc: true
    toc_float: true
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}
library(tidyverse)
library(tidymodels)
library(tune)
library(glmnet)
library(baguette)
library(parsnip)
library(doParallel)
library(vip)
library(pdp)
library(patchwork)
library(ranger)
library(future)
```

## Data 

```{r, include=TRUE}
set.seed(3000)
data <- read_csv(here::here("data", "train.csv")) %>% 
  select(-classification)

data <- dplyr::sample_frac(data, size = 0.01)

sheets <- readxl::excel_sheets(here::here("data",
"fallmembershipreport_20192020.xlsx"))

ode_schools <- readxl::read_xlsx(here::here("data",
"fallmembershipreport_20192020.xlsx"), sheet = sheets[4])

ethnicities <- ode_schools %>%
select(attnd_schl_inst_id = `Attending School ID`,
sch_name = `School Name`,
contains("%")) %>%
janitor::clean_names()
names(ethnicities) <- gsub("x2019_20_percent", "p", names(ethnicities))

data <- left_join(data, ethnicities)
head(data)
colnames(data)
data %>% 
  select(sch_name)
```

## Split and Resample 

```{r, include=TRUE}
set.seed(3000)
data_split <- initial_split(data, strata = "score")

set.seed(3000)
train <- training(data_split)
test <- testing(data_split)

set.seed(3000)
data_cv <- vfold_cv(train, strata = "score")

```

## Preprocess 

```{r, include=TRUE}
rec <- recipe(
    formula = score ~ ., data = train 
  ) %>%
 step_mutate(tst_dt = lubridate::mdy_hms(tst_dt)) %>%
 update_role(contains("id"), ncessch, sch_name, new_role = "id") %>%
 step_novel(all_nominal(), -all_outcomes()) %>%
 step_unknown(all_nominal(), -all_outcomes()) %>%
 step_medianimpute(all_numeric()) %>%
 step_nzv(all_predictors(), freq_cut = 0, unique_cut = 0) %>%
 step_dummy(all_nominal(), -has_role(match = "id"), -all_outcomes()) %>%
 step_nzv(all_predictors())



prep(rec)  
```


## Model and Workflow

```{r, include=TRUE}

metrics_eval <- metric_set(rmse,
                           rsq,
                           huber_loss)

bag_model_tune <- bag_tree() %>% 
  set_mode("regression") %>% 
  set_args(cost_complexity = tune(), min_n = tune()) %>% 
  set_engine("rpart", times = 10) 

bagged_wflow <- workflow() %>%
add_recipe(rec) %>%
add_model(bag_model_tune)



tree_grid <- grid_max_entropy(cost_complexity(), min_n(), size = 10) 

plan(multisession) 
tictoc::tic()
bag_tune <- tune_grid(bag_model_tune,
                      rec,
                      data_cv,
                      grid = tree_grid,
                      metrics = metrics_eval, 
                      control = control_resamples(verbose = TRUE,
                                                  save_pred = TRUE,
                                                  extract = function(x) extract_model(x)))
tictoc::toc()




```

## Best Estimates 


```{r, include=TRUE}
show_best(bag_tune, "rmse")
select_best(bag_tune, "rmse")

show_best(bag_tune, "rsq")
select_best(bag_tune, "rsq")

show_best(bag_tune, "huber_loss")
select_best(bag_tune, "huber_loss")
```

## Bag Roots Function

```{r, include=TRUE}
bag_roots <- function(x){
  x %>% 
  select(.extracts) %>% 
  unnest(cols = c(.extracts)) %>% 
  mutate(models = map(.extracts,
                  ~.x$model_df)) %>% 
  select(-.extracts) %>% 
  unnest(cols = c(models)) %>% 
  mutate(root = map_chr(model,
                     ~as.character(.x$fit$frame[1, 1]))) %>%
  select(root)  
}

bag_roots(bag_tune)

root <- bag_roots(bag_tune)

```

## Plot

```{r, include=TRUE}


root_count <- root %>% 
  count(root)

ggplot(root_count, aes(fct_reorder(root, n), n)) +
  geom_col() +
  coord_flip()

```
